<?php
class Book{
    protected $id;
    protected $name;
    protected $title;
    protected $author;
    protected $publicationYear;
    protected $type;

    public function __construct($id, $name, $title, $author, $publicationYear, $type) {
        $this->id = $id;
        $this->name = $name;
        $this->title = $title;
        $this->author = $author;
        $this->publicationYear = $publicationYear;
        $this->type = $type;
    }
    public function setId($id){
    $this->id = $id;
    }
    public function setName($name){
        $this->name = $name;
    }
    public function setTitle($title){
        $this->title = $title;
    }
    public function setAuthor($author){
        $this->author = $author;
    }
    public function setPublicationYear($publicationyear){
        $this->publicationYear = $publicationyear;
    }
    public function setType($type){
        $this->type = $type;
    }

    public function getId(){
        return $this->id;
    }
    public function getName(){
        return $this->name;
    }
    public function getTitle(){
        return $this->title;
    }
    public function getAuthor(){
        return $this->author;
    }
    public function getPublicationYear(){
        return $this->publicationYearr;
    }
    public function getType(){
        return $this->type;
    }

    public function printBookInfo() {
        echo "Tên sách: {$this->name}\n";
        echo "Tiêu đề: {$this->title}\n";
        echo "Tác giả: {$this->author}\n";
        echo "Năm xuất bản: {$this->publicationYear}\n";
    }
}

class PaperBook extends Book{
    private $weight;
    public function __construct($id, $name, $title, $author, $publicationYear, $type, $weight)
    {
        parent::__construct($id, $name, $title, $author, $publicationYear, $type);
        $this->weight = $weight;
    }

    public function setWeight($weight){
        $this->weight = $weight;
    }
    public function getWeight($weight){
        return $this->weight;
    }
    public function printBookInfo()
    {
        parent::printBookInfo(); // TODO: Change the autogenerated stub
        echo "Trọng lương: {$this->weight} kg\n";
    }
}

class EBook extends Book{
    private $size;
    public function __construct($id, $name, $title, $author, $publicationYear, $type, $size)
    {
        parent::__construct($id, $name, $title, $author, $publicationYear, $type);
        $this->size = $size;
    }

    public function setSize($size){
        $this->size = $size;
    }
    public function getSize(){
        return $this->size;
    }
    public function printBookInfo()
    {
        parent::printBookInfo(); // TODO: Change the autogenerated stub
        echo "Dung lượng tệp: {$this->size} MB\n";
    }
}
