<?php
class Book{
    protected $id;
    protected $name;
    protected $title;
    protected $author;
    protected $publicationYear;
    protected $type;

    public function __construct($id, $name, $title, $author, $publicationYear, $type) {
        $this->id = $id;
        $this->name = $name;
        $this->title = $title;
        $this->author = $author;
        $this->publicationYear = $publicationYear;
        $this->type = $type;
    }
    public function setId($id){
    $this->id = $id;
    }
    public function setName($name){
        $this->name = $name;
    }
    public function setTitle($title){
        $this->title = $title;
    }
    public function setAuthor($author){
        $this->author = $author;
    }
    public function setPublicationYear($publicationyear){
        $this->publicationYear = $publicationyear;
    }
    public function setType($type){
        $this->type = $type;
    }

    public function getId(){
        return $this->id;
    }
    public function getName(){
        return $this->name;
    }
    public function getTitle(){
        return $this->title;
    }
    public function getAuthor(){
        return $this->author;
    }
    public function getPublicationYear(){
        return $this->publicationYearr;
    }
    public function getType(){
        return $this->type;
    }

    public function printBookInfo() {
        echo "Tên sách: {$this->name} <br>";
        echo "Tiêu đề: {$this->title} <br>";
        echo "Tác giả: {$this->author} <br>";
        echo "Năm xuất bản: {$this->publicationYear} <br>";
    }
}

class PaperBook extends Book{
    private $weight;
    public function __construct($id, $name, $title, $author, $publicationYear, $type, $weight)
    {
        parent::__construct($id, $name, $title, $author, $publicationYear, $type);
        $this->weight = $weight;
    }

    public function setWeight($weight){
        $this->weight = $weight;
    }
    public function getWeight($weight){
        return $this->weight;
    }
    public function printBookInfo()
    {
        parent::printBookInfo(); // TODO: Change the autogenerated stub
        echo "Trọng lương: {$this->weight} kg <br>";
    }
}

class EBook extends Book{
    private $size;
    public function __construct($id, $name, $title, $author, $publicationYear, $type, $size)
    {
        parent::__construct($id, $name, $title, $author, $publicationYear, $type);
        $this->size = $size;
    }

    public function setSize($size){
        $this->size = $size;
    }
    public function getSize(){
        return $this->size;
    }
    public function printBookInfo()
    {
        parent::printBookInfo(); // TODO: Change the autogenerated stub
        echo "Dung lượng tệp: {$this->size} MB <br>";
    }
}

$book = new Book("01", "Doremon", "Truyện", "ABC", "2003", "Truyện Tranh");
$book->setId("01");
$book->setName("Doremon");
$book->setTitle("Truyện");
$book->setAuthor("ABC");
$book->setPublicationYear("2003");
$book->setType("Truyện Tranh");
$book->printBookInfo();
echo "---------------------------------";
echo "<br>";
$paperBook = new PaperBook("01", "Doremon", "Truyện", "ABC", "2003", "Truyện Tranh", 0.045);
$paperBook->setWeight(0.045);
$paperBook->printBookInfo();
echo "---------------------------------";
echo "<br>";
$eBook = new EBook("01", "Doremon", "Truyện", "ABC", "2003", "Truyện Tranh", 10);
$eBook->setSize(10);
$eBook->printBookInfo();



